version: "3.9"

services:

  pgadmin4:
    container_name: "pgadmin4"
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@email.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "9090:80"
    depends_on:
      - postgres
    networks:
      - container

  postgres:
    container_name: "postgres"
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - container

networks:
  container:
    driver: bridge